// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  generator: {
    client: {
      provider: "prisma-client-js",
    },
  },
  seed: {
    typescript: "npx tsx prisma/seed.ts",
  },
  datasource: {
    url: "file:./prisma/dev.db",
  },
});
